PAR_MONITORADO = [
  "PETR4", "ITSA3", "BBDC3", "ABEV3"
]

ACAO_LOWER_LIMIT0 = 35.00
ACAO_LOWER_LIMIT1 = 12.72
ACAO_LOWER_LIMIT2 = 16.87
ACAO_LOWER_LIMIT3 = 14.74

LOWER_ALERT_KEY0 = f"{PAR_MONITORADO[0]}"
LOWER_ALERT_KEY1 = f"{PAR_MONITORADO[1]}"
LOWER_ALERT_KEY2 = f"{PAR_MONITORADO[2]}"
LOWER_ALERT_KEY3 = f"{PAR_MONITORADO[3]}"
